### ISSUE TITLE
CRITICAL: Unable to install this app.

### ISSUE THREAD

**Issue by NagariaHussain** [quantumbitcore/erpnext-restaurant#2]
Frappe/ERPNext Version: Version 13

During `get-app`:

```
Installing restaurant_management
$ ./env/bin/python -m pip install -q -U -e ./apps/restaurant_management
ERROR: Could not find a version that satisfies the requirement frappe_helper (from restaurant-management) (from versions: none)
ERROR: No matching distribution found for frappe_helper
```

The problem is with `requirements.txt`:

<img width="421" alt="Screenshot 2021-12-06 at 1 44 42 PM" src="https://user-images.githubusercontent.com/34810212/144810965-1bdfaa2e-7796-4b9f-a50d-22642df9d2b0.png">

This dependencies should not be put in `requirements.txt`. This are already present in bench, removing these should fix the issue.

**Comment by NagariaHussain** [comment]
Please resolve this issue, so we can get this app on Frappe Cloud Marketplace. @quantumbitcore

**Comment by quantumbitcore** [comment]
perfect, thanks for the suggestion.

**Comment by umairsy** [comment]
Thanks for an application to list on FC Marketplace. Looking forward to getting it published.
