### ISSUE TITLE
desk form restaurant-room not found

### ISSUE THREAD

**Issue by webbosolutions** [quantumbitcore/erpnext-restaurant#20]
hello 
1- iam always see this notification when i edit restaurant name or table 
2- after add new restaurant i must refresh page to show it
thanks
![12122333](https://user-images.githubusercontent.com/48894929/178537650-f2cedd22-02fe-4b38-bd95-5d3134d68936.JPG)

**Comment by quantumbitcore** [comment]
Please download the latest update, from frappe_helper and restaurant app, then run migrate and lastly run the reinstall button in restaurant settings.

**Comment by quantumbitcore** [comment]
Do you mean After add new table or room?

**Comment by quantumbitcore** [comment]
If is your case you need set your server (not frappe) in production.

**Comment by webbosolutions** [comment]
i made reinstall and resolved thanks
i have other issue please
after add item to order not see on production center also how i arrange status in production center(kitchen)

Sincerely

**Comment by quantumbitcore** [comment]
To see the orders in the production center, you must first establish what states and what items the production center is going to handle, of course, order the order must be executed so that each item begins its process

**Comment by quantumbitcore** [comment]
The first status of the item in the order is pending, the next is shipped, if your production center handles the shipped status, it will be reflected.  States are created in the center of production in a scalar way.  for example:
Pending  to confirm, 
confirm to preparing, 
preparing -to ompleted.

**Comment by webbosolutions** [comment]
thanks thanks working now
