### ISSUE TITLE
Closing Pos Amount

### ISSUE THREAD

**Issue by webbosolutions** [quantumbitcore/erpnext-restaurant#21]
hello
I tried To Close Pos Profile but not showing all my pos real amount its give me closing amount 0 although i already have orders .
thanks

**Comment by quantumbitcore** [comment]
have you invoiced your orders?

**Comment by webbosolutions** [comment]
I only did normal pos orders and pay after that closed pos profile 
tell me please what is the way?

**Comment by quantumbitcore** [comment]
ok i will do a test and let you know

**Comment by webbosolutions** [comment]
thanks for reply

**Comment by webbosolutions** [comment]
hello
any updates please

**Comment by quantumbitcore** [comment]
I'm sorry, I haven't been able to review it yet, I'll update in a few hours.

**Comment by quantumbitcore** [comment]
Please let's discuss this to develop properly

**Comment by webbosolutions** [comment]
hello thanks for reply
I  want to use the same structure as POS Erpnext
we need after closing pos restaurant calculate all restaurant orders only

thanks

**Comment by webbosolutions** [comment]
![545456698](https://user-images.githubusercontent.com/48894929/178845249-9f11b31c-e5b6-40f4-95ba-97a208e268f2.JPG)
 I tried to close pos but not give me real closing amount

**Comment by quantumbitcore** [comment]
Yes because erpenext uses the POS Invoice from POS, and at closing it does the reconciliation and creates the invoice.

**Comment by quantumbitcore** [comment]
In previous versions, they used the POS Invoice doctype directly.

**Comment by quantumbitcore** [comment]
Update is Ready in develop branch, please donwload, migrate and build.

**Comment by webbosolutions** [comment]
sorry i do updating but failed please check attached video
https://1drv.ms/v/s!ApPSBEF3azjDsUSJ8bJw6UETUdRJ?e=On6OU5

**Comment by quantumbitcore** [comment]
that is corrected, verify that you are in the develop Branch, then execute migrate and build.

**Comment by quantumbitcore** [comment]
Then set your pos Profile in restaurant settings

**Comment by webbosolutions** [comment]
sorry I am not professional in github I am always reinstall your app commands 
1- bench get-app https://github.com/quantumbitcore/erpnext-restaurant.git
2- bench --site mysite install-app restaurant_management
I don't know how i must install updates sorry?

**Comment by quantumbitcore** [comment]
Get me your WhatsApp please to send instructions.

**Comment by webbosolutions** [comment]
[64989897.txt](https://github.com/quantumbitcore/erpnext-restaurant/files/9115675/64989897.txt)

**Comment by quantumbitcore** [comment]
you cand do in your frappe-bench:
cd apps/restaurant_management
git checkout develop

then execute: 
bench migrate
bench build --app restaurant_management
