### ISSUE TITLE
Installed but not visible in modules

### ISSUE THREAD

**Issue by gsbaig** [quantumbitcore/erpnext-restaurant#33]
hello

I am installing your app abd after the isntallation its not visibble any were. how i can propelry configure it.

Thanks

**Comment by quantumbitcore** [comment]
In what version of frappé do you have it installed?

**Comment by gsbaig** [comment]
version 14

**Comment by quantumbitcore** [comment]
Ok, I need to work out some details for version 14, including just that bug.

**Comment by quantumbitcore** [comment]
Please you can test in version 13 for now.

**Comment by gsbaig** [comment]
First of all i thanks you for the replies

if you can give some idea i can try to sort for version 14

**Comment by greekrode** [comment]
Hi @quantumbitcore, is there any update regarding this?

**Comment by quantumbitcore** [comment]
Update and try please.
