### ISSUE TITLE
Notes: The text is not consistent to what is typed in fast mode.

### ISSUE THREAD

**Issue by mujeerhashmi** [quantumbitcore/erpnext-restaurant#36]
When we type fast and delete some characters in notes then the next typed characters disappear. This will have problems in a fast-paced restaurant.

The notes should not be allowed to change when the order is confirmed in the kitchen.

**Comment by quantumbitcore** [comment]
Can you send me a printscreen please.

**Comment by quantumbitcore** [comment]
It was already fixed.
