### ISSUE TITLE
Clicking on table show blank page with table name

### ISSUE THREAD

**Issue by ggiraudon** [quantumbitcore/erpnext-restaurant#39]
Hi.

I'm trying to install the project on a Debian VM (Debian Bullseye)

Here are the steps I've taken from a fresh install :

Install base packages and configure MariaDB 

apt install curl git sudo
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
apt update
apt install -y nodejs mariadb-server redis-server python3-pip nginx python3-testresources python3-distutils python3-setuptools python3.9-venv libssl-dev wkhtmltopdf supervisor
mariadb-secure-installation
adduser erp
adduser erp sudo
modified /etc/mysql/my.cnf for collation settings
modified /etc/mysql/mariadb.conf.d/50-server.cnf for collation settings
service mysql restart

Switch to "erp" user and install a frappe bench :

su erp
sudo npm install -g yarn
pip3 install frappe-bench
export PATH=$PATH:/home/erp/.local/bin
sudo pip3 install frappe-bench
bench init --frappe-branch version-13 frappe-bench
cd frappe-bench/

Install ERPNext

bench new-site site1.local
bench get-app --branch version-13 erpnext
bench --site site1.local install-app erpnext
sudo bench setup production erp
cp config/supervisor.conf /etc/supervisor/conf.d/

Installed Frapper Helper

bench get-app https://github.com/quantumbitcore/frappe_helper.git
bench setup requirements
bench build --app frappe_helper
bench --site site1.local install-app frappe_helper
bench --site site1.local migrate
sudo service supervisor restart

Installed ERPNext-Restaurante

bench get-app https://github.com/quantumbitcore/erpnext-restaurant.git
bench setup requirements
bench build --app restaurant_management
sudo service supervisor restart
bench --site site1.local install-app restaurant_management
bench --site site1.local migrate
bench build
bench clear-cache
bench --site site1.local clear-cache
sudo service supervisor restart

After the install, I've completed the setup on the portal by logging in as administrator, went into the "Restaurant management section" , create a room, a table and production center.
I also created a bunch of products under "stock" -> "items"

When I go into the "Restaurant Management" -> "Restaurant" screen, I see the room and the table.
If I click on the table, this is what I see :

![image](https://user-images.githubusercontent.com/326556/209452935-b8f05850-fcfe-411f-bb3e-13b08ed44910.png)

I'm not sure what to do next or where to look to troubleshoot this issue.
The supervisor services seem to run fine. This is the output of "supervisorctl"

frappe-bench-redis:frappe-bench-redis-cache                 RUNNING   pid 22656, uptime 0:09:16
frappe-bench-redis:frappe-bench-redis-queue                 RUNNING   pid 22657, uptime 0:09:16
frappe-bench-redis:frappe-bench-redis-socketio              RUNNING   pid 22658, uptime 0:09:16
frappe-bench-web:frappe-bench-frappe-web                    RUNNING   pid 22659, uptime 0:09:16
frappe-bench-web:frappe-bench-node-socketio                 RUNNING   pid 22660, uptime 0:09:16
frappe-bench-workers:frappe-bench-frappe-default-worker-0   RUNNING   pid 22662, uptime 0:09:16
frappe-bench-workers:frappe-bench-frappe-long-worker-0      RUNNING   pid 22664, uptime 0:09:16
frappe-bench-workers:frappe-bench-frappe-schedule           RUNNING   pid 22661, uptime 0:09:16
frappe-bench-workers:frappe-bench-frappe-short-worker-0     RUNNING   pid 22663, uptime 0:09:16

I've also noticed that if I try to add a table in the "Restaurant" UI, it doesnt show up immediately. I have to refresh the window for it to show up.

I've checked the browser logs and network requests and nothing seems to be missing.
There is a websocket opening but not much activity there.

When clicking on a table in the Restaurant view, there are 3 ajax calls being made.

The first one to /api/method/erpnext.selling.page.point_of_sale.point_of_sale.check_opening_entry
Which returns :
{"message":[{"name":"POS-OPE-2022-00001","company":"Arawak","pos_profile":"Demo POS Profile","period_start_date":"2022-12-24 16:49:14.015767"}]}

The second one to /api/method/frappe.client.get_value?doctype=Stock+Settings&fieldname=allow_negative_stock&_=1671921703759
Which returns :
{"message":{"allow_negative_stock":"0"}}

The thrids one to /api/method/frappe.client.get?doctype=POS+Profile&name=Demo+POS+Profile&_=1671921703760
Which returns :
{"message":{"name":"Demo POS Profile","owner":"demo@demo.demo","creation":"2022-12-24 15:58:17.192876","modified":"2022-12-24 15:58:17.192876","modified_by":"demo@demo.demo","parent":null,"parentfield":null,"parenttype":null,"idx":0,"docstatus":0,"company":"Arawak","customer":null,"country":"Anguilla","disabled":0,"warehouse":"Finished Goods - ARK","campaign":null,"company_address":null,"hide_images":0,"hide_unavailable_items":0,"auto_add_item_to_cart":0,"validate_stock_on_save":0,"update_stock":1,"ignore_pricing_rule":0,"allow_rate_change":0,"allow_discount_change":0,"print_format":null,"letter_head":null,"tc_name":null,"select_print_heading":null,"selling_price_list":"Standard Selling","currency":"XCD","write_off_account":"Write Off - ARK","write_off_cost_center":"Main - ARK","write_off_limit":1.0,"account_for_change_amount":null,"disable_rounded_total":0,"income_account":null,"expense_account":null,"taxes_and_charges":null,"tax_category":null,"posa_tax_inclusive":0,"apply_discount_on":"Grand Total","cost_center":null,"doctype":"POS Profile","applicable_for_users":[],"payments":[{"name":"bfe701452b","owner":"demo@demo.demo","creation":"2022-12-24 15:58:17.192876","modified":"2022-12-24 15:58:17.192876","modified_by":"demo@demo.demo","parent":"Demo POS Profile","parentfield":"payments","parenttype":"POS Profile","idx":1,"docstatus":0,"default":1,"allow_in_returns":0,"mode_of_payment":"Credit Card","doctype":"POS Payment Method"},{"name":"cf13f8a050","owner":"demo@demo.demo","creation":"2022-12-24 15:58:17.192876","modified":"2022-12-24 15:58:17.192876","modified_by":"demo@demo.demo","parent":"Demo POS Profile","parentfield":"payments","parenttype":"POS Profile","idx":2,"docstatus":0,"default":0,"allow_in_returns":0,"mode_of_payment":"Cash","doctype":"POS Payment Method"}],"item_groups":[],"customer_groups":[]}}

Have I missed something in the configuration ?

PS : I also tried installing the "develop" branch but that didnt make a difference

Any pointers as to what could be going on would be greatly appreciated.

**Comment by ggiraudon** [comment]
Just as a quick update: I made sure to assign "status managed" and "item groups" to the rooms and tables.
I also tried creating an order via app/table-order to see if it would change something on  the "Restaurant' view.
No luck

**Comment by quantumbitcore** [comment]
Hi, you have installed in server? Can you send me your credentials please.

**Comment by quantumbitcore** [comment]
I can help you to resolve.

**Comment by ggiraudon** [comment]
Hi quantumbitcore !
That's very nice of you.
I'll pm you with the credentials

**Comment by ggiraudon** [comment]
It looks like I can't send you PM. So here's the credentials for the test server :

Server : erpnext.prism19.com
User : erp
Pass : @sunshine22

In the ERP itself, there's a single account : 
demo@demo.demo
Pass : demo

All passwords are set to @sunshine22

Let me know what you find :)

**Comment by quantumbitcore** [comment]
I'm sorry for the delay, let me solve today and I'll let you know.

**Comment by ggiraudon** [comment]
No problem at all. It's very kind of you to help. Let me know if you need anything.

**Comment by quantumbitcore** [comment]
I'm checking right now

**Comment by quantumbitcore** [comment]
Sorry, an update was missing from the repository, it's resolved.

**Comment by ggiraudon** [comment]
It worked perfectly. Thank you so much. Amazing work.
