### ISSUE TITLE
UI not updating 

### ISSUE THREAD

**Issue by asamawi** [quantumbitcore/erpnext-restaurant#4]
UI not updating new order creation , order deletion, and other actions. Things get done in the background and you have to refresh manually or reopen the table to see changes.

**Comment by quantumbitcore** [comment]
It is possible that your server is in dev mode.

If that's the case, sorry I couldn't get the socket to work in dev mode, it works only with the production server.

**Comment by asamawi** [comment]
The server is not in dev mode. Frappe helper is installed. Maybe some missing dependency ??

**Comment by quantumbitcore** [comment]
Ok, I don't know what could be happening. I would have to see the console.

**Comment by asamawi** [comment]
Https://demo.n4s-solutions.com

**Comment by kanu2005** [comment]
I have the same problem, please explain how to fix it

**Comment by kanu2005** [comment]
> I have the same problem, please explain how to fix it


I have the same problem, please explain how to fix it

im need help

**Comment by quantumbitcore** [comment]
ok problem Solved
Remember, This app works 100% in real time, and the socket.io does not work when the server (not frappe) is in development mode, the server must be in production mode.

**Comment by asamawi** [comment]
Problem fixed after setting server in production, I ran  the bellow code in bench directory:
`sudo bench setup production [BENCH USER]`
`sudo supervisorctl restart all`

**Comment by quantumbitcore** [comment]
Yes Sr.
