### ISSUE TITLE
Item search and item group filter not working

### ISSUE THREAD

**Issue by AlaaBadry** [quantumbitcore/erpnext-restaurant#6]
Item search and item group filter not working 
can't search for items and not all items appear

**Comment by quantumbitcore** [comment]
I am testing.

**Comment by AlaaBadry** [comment]
I fixed if you want i will push the fixed update

**Comment by quantumbitcore** [comment]
Perfect AllaBadry, you can.

**Comment by AlaaBadry** [comment]
Okay i will and please share your contact to discuss some issue about the
app

**Comment by AlaaBadry** [comment]
> Perfect AllaBadry, you can.

please check pull request

**Comment by AlaaBadry** [comment]
Solved and migrated
