### ISSUE TITLE
Printing Format

### ISSUE THREAD

**Issue by webbosolutions** [quantumbitcore/erpnext-restaurant#7]
hi
i want to change printing format but for pay not for account 
please

**Comment by quantumbitcore** [comment]
you can create your own print format in erpnext "app/print-format", then configure it in your active POS Profile. The billing of the restaurant is the same as that of the ERPNext POS.

**Comment by quantumbitcore** [comment]
Currently I know that ERPNext does not generate invoices directly, but rather creates them until the POS Profile is closed, that is an issue that needs review. When I created the restaurant module, they generated the invoice directly. In other words, for each invoice created in the POS, a record was created in the Doctype Invoice, currently it is created in the POS Invoice.

**Comment by AlaaBadry** [comment]
> RPNext POS

no, it's not working I try to add print format in pos profile but not appear in pay print

**Comment by webbosolutions** [comment]
> When I created the restaurant module, they generated the invoice directly

okay but any solution for that

**Comment by quantumbitcore** [comment]
the solution is simple, use the POS Invoice doctype, but it depends on the version of Erpnext that is going to be used. 

About the printing format I review and update.

**Comment by AlaaBadry** [comment]
> the solution is simple, use the POS Invoice doctype, but it depends on the version of Erpnext that is going to be used.
> 
> About the printing format I review and update.

i add the default print format for POS invoice doctype but not reflected in the payment print format its generates the stander print format for invoice doctype

**Comment by webbosolutions** [comment]
hi bro
is there any update or any solution regarding printing format

**Comment by quantumbitcore** [comment]
It's ready, then it will be uploaded.

**Comment by quantumbitcore** [comment]
Yeah, it's ready; but the update was rolled back to correct the search, because there was a conflict. It will update again but the print format update is available.
